Repository blurry-x-face/DailyFoss, pull requests merged in 2019-11, with the labels that each got.

#6 login ui
  ui.html
Labels: Easy, getsetfoss2019

#20 Ui login
  Screenshot from 2019-11-05 01-53-56.png
  codepen login
Labels: Easy, getsetfoss2019

#17 my calculator
  MIGHTY CALCULATOR
Labels: Medium, getsetfoss2019

#24 Login UI Page
  Login UI Page
Labels: Easy, getsetfoss2019

#36 login ui page
  login ui page
Labels: Easy, getsetfoss2019

#33 Subhash2807 patch 2
  An.png
  OSpGtA7jQi.jpg
  calc page link.txt
  login page link.txt
Labels: Medium, getsetfoss2019

#49 Calculator
  CALCULATOR_LCS2019022.html
Labels: Medium, getsetfoss2019

#7 login ui
  Screenshot (1).png
Labels: Easy, getsetfoss2019

#8 login ui
  login ui
Labels: Easy, getsetfoss2019

#9 login form ui
  login form ui
Labels: Easy, getsetfoss2019

#11 login UI page
  px.html
Labels: Easy, getsetfoss2019

#13 login page UI
  log.html
Labels: Easy, getsetfoss2019

#14 Ashu1
  Screenshot (30).png
  index.html
Labels: Easy, getsetfoss2019

#44 Calculator to perform basic arithmetic operations
  calculator.html
Labels: Medium, getsetfoss2019

#46 Royal3
  login2.PNG
Labels: Easy, getsetfoss2019

#50 Calculator(Calculator App (due date: 5 Nov 2019))
  Calculator/calcharsh.css
  Calculator/calcharsh.html
  chrome_R51tmBJIDa.png
Labels: Medium, getsetfoss2019

#58 My weather web app by nawab-shah
  My-Weather/main.css
  My-Weather/main.html
  My-Weather/main.js
  main.css
  main.html
  main.js
Labels: Hard, getsetfoss2019

#52 Article on Chrome DevTools completed #39
  chrome_devtools_article_link.txt
Labels: Hard, getsetfoss2019

#55 exploring chrome developer tools
  exploring chrome developer tools
Labels: Hard, getsetfoss2019

#53 https://codepen.io/genjutsumaster/pen/BaaVwBe
  awsm.PNG
  calculator.html
  style.css
Labels: Medium, getsetfoss2019

#64 created rail website
  railway website
Labels: Hard, getsetfoss2019

#71 raliways portal
  Screenshot from 2019-11-22 19-14-44.png
  Screenshot from 2019-11-22 19-14-48.png
  Screenshot from 2019-11-22 19-14-52.png
Labels: Extra, getsetfoss2019

#77 Railway Booking Portal
  Railway Booking Portal
Labels: Extra, getsetfoss2019

#76 railway portal by moin
  Screenshot (36).png
Labels: getsetfoss2019, very easy

#78 created rail website
  {87C2D110-414A-4BD4-A98A-9E0177DFC6C1}.png.jpg
Labels: Easy, getsetfoss2019

#70 my portfolio
  Screenshot from 2019-11-22 17-14-48.png
  Screenshot from 2019-11-22 17-14-54.png
  Screenshot from 2019-11-22 17-15-28.png
Labels: Easy, getsetfoss2019

#79 Add files via upload
  Screenshot from 2019-11-23 19-23-56.png
  Screenshot from 2019-11-23 19-24-16.png
  www
Labels: getsetfoss2019, very easy

#80 Portfolioashu1
  Screenshot (60).png
  Screenshot (61).png
Labels: getsetfoss2019, pro
